#!/bin/bash

for i in {0..4}; do
    echo $i
    ./dict_matching_test patterns/dna/dna_100_400_$i dna.50MB $1 >> results/dict_matching/dna/dna_alpha_$1
done

git add .
git commit -m "Added results for alpha value $1"
