#!/bin/bash

        for i in {0..4}; do
            file="patterns/$1/$1"
            file+="_$2"
            file+="_$3"
            file+="_$i"
            ./gen_pattern_set $2 $3 $1.50MB $file
        done
