#!/usr/bin/python
import random
import sys

num_patterns = int(sys.argv[1])
max_length = int(sys.argv[2])

with open(sys.argv[3], 'r') as text:
    line = text.read()
    with open(sys.argv[4], 'w') as patterns:
        patterns.write("%d\n" % num_patterns)
        for i in range(num_patterns):
            length = random.randint(1, max_length + 1)
            end = random.randint(length, len(line))
            patterns.write("%d\n" % length)
            patterns.write("%s\n" % line[end - length:end])
